version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
      #dotnet: latest - Latest resolve to 3.1, check this issue https://github.com/aws/aws-codebuild-docker-images/issues/414

  pre_build:
    commands:
      - dotnet --list-sdks
      - dotnet restore ./SimpleAWSTest5.0API.csproj
  
  build:
    commands:
      - echo Build started on `date`
      - dotnet build

artifacts:
  files:
    - ./**/*
